language: c
sudo: required
before_install:
  - sudo add-apt-repository ppa:wfg/0ad.dev -y
  - sudo apt-get update -q
  - sudo apt-get install -y libsodium-dev libzmq3-dev m4 pkg-config
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
os:
  - linux